### ISSUE TITLE
Smooth Out Stairs all blurry

### ISSUE THREAD

**Issue by Raylo555** [relaxtakenotes/addon-issues#10]
"Smooth Out Stairs" has some weird Blurring effect when moving up stairs or even just Landing from a jump.

**Comment by relaxtakenotes** [comment]
can you elaborate what you mean by blurry or show it with a video

**Comment by Raylo555** [comment]
Here, idk what's causing it.
https://youtu.be/yRXfgPCmXBo

**Comment by Raylo555** [comment]
And before you say it's a mod conflict, I then tested it with two mods installed, the smooth stairs and my mewtwo playermodel.
The same thing was happening.

**Comment by relaxtakenotes** [comment]
you can temporarily try to fix this by capping your fps to something under 200. however i know what causes this and it'll be fixed when i can get around to it

**Comment by Raylo555** [comment]
I actually have my FPS limited to 150.

**Comment by relaxtakenotes** [comment]
then try playing on x64, which is a better version in every way. timer resolution could also be at play but don't play around with that unless you really wanna

**Comment by Raylo555** [comment]
nah I'll just wait for a fix, it's not world ending that I don't have smoother stairs.

**Comment by relaxtakenotes** [comment]
pushed the fix to the workshop. i didnt test or even run the game with the mod enabled so tell me if you have any issues
