### ISSUE TITLE
[Better Movement] Strange "snapping" after sprinting on MWB viewmodels

### ISSUE THREAD

**Issue by Syampuuh** [relaxtakenotes/addon-issues#2]
Yes, I know, Modern Warfare Base is kind of its own enigma of compatibility issues, but I figure it is worth at least asking about.

When using Better Movement, there is a bit of "snap" as the viewmodel goes from sprinting to idle or walking. No settings within Better Movement seem to affect it, other than disabling it. Here is a demonstration with only MWB, the official guns, and Better Movement enabled:

https://github.com/relaxtakenotes/addon-issues/assets/25516124/0867585e-d968-4fde-8d53-d8040dd65de3

**Comment by relaxtakenotes** [comment]
yeah ik. it's fixed in the 192319023th refactor of better movement
