### ISSUE TITLE
Гранаты в моде ARC9 EFT Grenades невидимые

### ISSUE THREAD

**Issue by Maykr1337** [relaxtakenotes/addon-issues#5]
Когда бросаешь гранату с этим модом они не отрисовуются, но существуют. Возможно ли это пофиксить?

**Comment by relaxtakenotes** [comment]
каким?

**Comment by Maykr1337** [comment]
ARC9 EFT Grenades

**Comment by relaxtakenotes** [comment]
не буду маяться фиксить то, что ломается... сюрприз сюрприз, очень сильно ломающей фичей!
