### ISSUE TITLE
support for enchanced camera?

### ISSUE THREAD

**Issue by FEXlol** [relaxtakenotes/addon-issues#6]
i really dont know what else to say, any chance you can try to add support for this mod?

currently only the camera tilts but doesnt move.

**Comment by relaxtakenotes** [comment]
what mod r u talking about

**Comment by FEXlol** [comment]
didnt check the github repo name, sorry.
https://steamcommunity.com/sharedfiles/filedetails/?id=3138563659

**Comment by relaxtakenotes** [comment]
no support for it is intended unless i figure out a way to make viewoffset work in a certain way and keep it predicted

**Comment by FEXlol** [comment]
sad

**Comment by FEXlol** [comment]
@relaxtakenotes i meant Dynamic Height 2, wrong mod. https://steamcommunity.com/sharedfiles/filedetails/?id=3050234499

**Comment by relaxtakenotes** [comment]
same thing sadly

**Comment by FEXlol** [comment]
truly disastrous
